// Build-time output for persisted operations: a manifest the server loads
// without parsing or validating, and TypeScript types for each
// operation's variables and result.
//
// Statement text is not in the manifest: it depends on variable values
// (a `where` present or null, cursors, limits) and on the request's
// claims, so it is compiled per request and cached (see the compile
// cache). What the manifest fixes is the document and its validation.

import {
  getNamedType,
  isEnumType,
  isInputObjectType,
  isInterfaceType,
  isListType,
  isNonNullType,
  isObjectType,
  isScalarType,
  isUnionType,
  Kind,
  parse,
  printSchema,
  lexicographicSortSchema,
  specifiedRules,
  typeFromAST,
  validate,
  visit,
  type DocumentNode,
  type FragmentDefinitionNode,
  type GraphQLCompositeType,
  type GraphQLInputType,
  type GraphQLNamedType,
  type GraphQLOutputType,
  type GraphQLSchema,
  type OperationDefinitionNode,
  type SelectionSetNode,
  type ValidationRule,
} from "graphql";
import { sha256 } from "./compile/hmac.js";

export interface OperationManifest {
  version: 1;
  /** Hash of the public schema the operations were validated against. */
  schemaHash: string;
  operations: Record<string, ManifestOperation>;
}

export interface ManifestOperation {
  name: string | undefined;
  kind: "query" | "mutation" | "subscription";
  /** Root fields, by response key. */
  rootFields: string[];
  /** The validated document, as a GraphQL AST without locations. */
  document: DocumentNode;
}

/** Hash of the schema clients see: a manifest is valid for it only. */
export function schemaHash(schema: GraphQLSchema): string {
  const bytes = sha256(
    new TextEncoder().encode(printSchema(lexicographicSortSchema(schema))),
  );
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Parse and validate persisted operations (id → source) into a manifest.
 * Throws with every problem at once.
 */
export function buildManifest(
  schema: GraphQLSchema,
  operations: Record<string, string>,
  rules: ValidationRule[] = [],
): OperationManifest {
  const out: Record<string, ManifestOperation> = {};
  const problems: string[] = [];
  for (const [id, source] of Object.entries(operations)) {
    let doc: DocumentNode;
    try {
      doc = parse(source, { noLocation: true });
    } catch (err) {
      problems.push(`${id}: ${(err as Error).message}`);
      continue;
    }
    const errors = validate(schema, doc, [...specifiedRules, ...rules]);
    if (errors.length > 0) {
      problems.push(`${id}: ${errors.map((e) => e.message).join("; ")}`);
      continue;
    }
    const ops = doc.definitions.filter(
      (d): d is OperationDefinitionNode => d.kind === Kind.OPERATION_DEFINITION,
    );
    if (ops.length !== 1) {
      problems.push(`${id}: a persisted operation holds exactly one operation`);
      continue;
    }
    const op = ops[0]!;
    out[id] = {
      name: op.name?.value,
      kind: op.operation,
      rootFields: op.selectionSet.selections.flatMap((s) =>
        s.kind === Kind.FIELD ? [s.alias?.value ?? s.name.value] : [],
      ),
      document: doc,
    };
  }
  if (problems.length > 0) {
    throw new Error(
      `invalid persisted operations:\n  ${problems.join("\n  ")}`,
    );
  }
  return { version: 1, schemaHash: schemaHash(schema), operations: out };
}

// ---------------------------------------------------------------------------
// TypeScript types
// ---------------------------------------------------------------------------

/** How scalars arrive in JSON results and variables. */
const SCALAR_TS: Record<string, string> = {
  String: "string",
  ID: "string",
  Int: "number",
  Float: "number",
  Boolean: "boolean",
  // Decimal strings and ISO-8601 temporals.
  BigInt: "string",
  Date: "string",
  Time: "string",
  LocalTime: "string",
  DateTime: "string",
  LocalDateTime: "string",
  Duration: "string",
};

/**
 * TypeScript declarations for each operation: `<Name>Variables` and
 * `<Name>Result`, plus the enums and input types they use. `ids` name the
 * operations (the manifest's ids when they have no operation name).
 */
export function generateTypes(
  schema: GraphQLSchema,
  manifest: OperationManifest,
  /** Custom scalars (`@storedAs`) and their storage types. */
  storage: ReadonlyMap<string, string> = new Map(),
): string {
  const named = new Map<string, string>();
  const lines: string[] = [
    "// Generated by lora-graphql compile. Do not edit.",
    "",
  ];

  const scalar = (t: GraphQLNamedType): string =>
    SCALAR_TS[t.name] ?? SCALAR_TS[storage.get(t.name) ?? ""] ?? "unknown";

  const enumType = (t: GraphQLNamedType): string => {
    if (!named.has(t.name) && isEnumType(t)) {
      named.set(
        t.name,
        `export type ${t.name} = ${t
          .getValues()
          .map((v) => JSON.stringify(v.name))
          .join(" | ")};`,
      );
    }
    return t.name;
  };

  const inputNamed = (t: GraphQLNamedType): string => {
    if (isScalarType(t)) return scalar(t);
    if (isEnumType(t)) return enumType(t);
    if (isInputObjectType(t) && !named.has(t.name)) {
      named.set(t.name, ""); // recursion guard
      const fields = Object.values(t.getFields()).map((f) => {
        const optional = !isNonNullType(f.type) || f.defaultValue !== undefined;
        return `  ${f.name}${optional ? "?" : ""}: ${input(f.type)};`;
      });
      named.set(
        t.name,
        `export interface ${t.name} {\n${fields.join("\n")}\n}`,
      );
    }
    return t.name;
  };

  const input = (t: GraphQLInputType): string => {
    if (isNonNullType(t)) return inputInner(t.ofType);
    return `${inputInner(t)} | null`;
  };
  const inputInner = (t: GraphQLInputType): string =>
    isListType(t)
      ? `Array<${input(t.ofType)}>`
      : inputNamed(getNamedType(t) as GraphQLNamedType);

  for (const [id, entry] of Object.entries(manifest.operations)) {
    const doc = entry.document;
    const op = doc.definitions.find(
      (d): d is OperationDefinitionNode => d.kind === Kind.OPERATION_DEFINITION,
    )!;
    const fragments = new Map(
      doc.definitions
        .filter(
          (d): d is FragmentDefinitionNode =>
            d.kind === Kind.FRAGMENT_DEFINITION,
        )
        .map((f) => [f.name.value, f]),
    );
    const base = typeName(op.name?.value ?? id);

    const vars = (op.variableDefinitions ?? []).map((v) => {
      const type = typeFromAST(schema, v.type) as GraphQLInputType;
      const optional = !isNonNullType(type) || v.defaultValue !== undefined;
      return `  ${v.variable.name.value}${optional ? "?" : ""}: ${input(type)};`;
    });
    lines.push(
      `export interface ${base}Variables {${vars.length ? `\n${vars.join("\n")}\n` : ""}}`,
      "",
    );

    const root =
      op.operation === "query"
        ? schema.getQueryType()!
        : op.operation === "mutation"
          ? schema.getMutationType()!
          : schema.getSubscriptionType()!;

    const output = (
      t: GraphQLOutputType,
      sets: SelectionSetNode[],
      depth: string,
    ): string => {
      if (isNonNullType(t)) return outputInner(t.ofType, sets, depth);
      return `${outputInner(t, sets, depth)} | null`;
    };
    const outputInner = (
      t: GraphQLOutputType,
      sets: SelectionSetNode[],
      depth: string,
    ): string => {
      if (isListType(t)) return `Array<${output(t.ofType, sets, depth)}>`;
      const n = getNamedType(t)!;
      if (isScalarType(n)) return scalar(n);
      if (isEnumType(n)) return enumType(n);
      return selection(n as GraphQLCompositeType, sets, depth);
    };

    /**
     * The object type selection sets produce on `parent`. Fields with the
     * same response key are merged as graphql-js merges them: one field,
     * with the sub-selections of every mention.
     */
    const selection = (
      parent: GraphQLCompositeType,
      sets: SelectionSetNode[],
      depth: string,
    ): string => {
      interface Mention {
        /** The field's output type, or the `__typename` literal union. */
        type: GraphQLOutputType | string;
        sets: SelectionSetNode[];
      }
      const fields = new Map<
        string,
        { mentions: Mention[]; optional: boolean }
      >();
      const add = (
        on: GraphQLCompositeType,
        s: SelectionSetNode,
        conditional: boolean,
      ) => {
        for (const sel of s.selections) {
          if (sel.kind === Kind.FIELD) {
            const key = sel.alias?.value ?? sel.name.value;
            let type: GraphQLOutputType | string;
            if (sel.name.value === "__typename") {
              type = possible(schema, on)
                .map((p) => JSON.stringify(p))
                .join(" | ");
            } else {
              const def =
                isObjectType(on) || isInterfaceType(on)
                  ? on.getFields()[sel.name.value]
                  : undefined;
              if (!def) continue;
              type = def.type;
            }
            const entry = fields.get(key) ?? { mentions: [], optional: true };
            // Same output type: one field whose selection is the union of
            // the mentions'. Different ones (members of an abstract type
            // with fields of different types) stay alternatives.
            const same = entry.mentions.find(
              (m) => String(m.type) === String(type),
            );
            if (same) {
              if (sel.selectionSet) same.sets.push(sel.selectionSet);
            } else {
              entry.mentions.push({
                type,
                sets: sel.selectionSet ? [sel.selectionSet] : [],
              });
            }
            entry.optional &&= conditional;
            fields.set(key, entry);
          } else if (sel.kind === Kind.INLINE_FRAGMENT) {
            const cond = sel.typeCondition
              ? (schema.getType(
                  sel.typeCondition.name.value,
                ) as GraphQLCompositeType)
              : on;
            add(cond, sel.selectionSet, conditional || cond !== on);
          } else {
            const frag = fragments.get(sel.name.value);
            if (!frag) continue;
            const cond = schema.getType(
              frag.typeCondition.name.value,
            ) as GraphQLCompositeType;
            add(cond, frag.selectionSet, conditional || cond !== on);
          }
        }
      };
      for (const set of sets) add(parent, set, false);
      const body = [...fields].map(([k, f]) => {
        const types = [
          ...new Set(
            f.mentions.map((m) =>
              typeof m.type === "string"
                ? m.type
                : output(m.type, m.sets, `${depth}  `),
            ),
          ),
        ];
        return `${depth}  ${k}${f.optional ? "?" : ""}: ${types.join(" | ")};`;
      });
      return `{\n${body.join("\n")}\n${depth}}`;
    };

    lines.push(
      `export interface ${base}Result ${selection(root, [op.selectionSet], "")}`,
      "",
    );
  }
  const declarations = [...named.values()].filter((d) => d.length > 0);
  return [
    ...lines.slice(0, 2),
    ...declarations.flatMap((d) => [d, ""]),
    ...lines.slice(2),
  ].join("\n");
}

function possible(schema: GraphQLSchema, t: GraphQLCompositeType): string[] {
  if (isObjectType(t)) return [t.name];
  if (isUnionType(t) || isInterfaceType(t)) {
    return schema.getPossibleTypes(t).map((p) => p.name);
  }
  return [];
}

/** `festivals-page#Top` → `FestivalsPageTop`. */
function typeName(id: string): string {
  const words = id.split(/[^A-Za-z0-9]+/).filter(Boolean);
  const name = words.map((w) => w[0]!.toUpperCase() + w.slice(1)).join("");
  return /^[0-9]/.test(name) ? `Op${name}` : name || "Operation";
}

/** Fragments reachable from `root`, transitively. */
export function usedFragments(
  root: OperationDefinitionNode,
  fragments: Map<string, FragmentDefinitionNode>,
): FragmentDefinitionNode[] {
  const seen = new Map<string, FragmentDefinitionNode>();
  const walk = (node: OperationDefinitionNode | FragmentDefinitionNode) =>
    visit(node, {
      FragmentSpread(spread) {
        const f = fragments.get(spread.name.value);
        if (f && !seen.has(f.name.value)) {
          seen.set(f.name.value, f);
          walk(f);
        }
      },
    });
  walk(root);
  return [...seen.values()];
}
