/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Lora graph database handle exposed to Node.
 *
 * Wraps an `Arc<Database<InMemoryGraph>>`; the same handle is cloned
 * onto the libuv threadpool for each `execute()` call. Multiple
 * concurrent queries against the same `Database` can share read-only
 * work; writes serialize on the inner store's write lock without
 * blocking the JS event loop.
 *
 * With no constructor arg the database is purely in-memory. Passing a
 * database name enables archive-backed persistence: the binding opens or
 * creates the serialized `.loradb` path under `database_dir` when supplied,
 * or the current directory otherwise. It replays committed writes on boot
 * and then serves queries against the recovered graph.
 */
export declare class Database {
  /**
   * Construct a database.
   *
   * - no args => fresh in-memory graph.
   * - `database_name` => archive-backed graph rooted at the serialized
   *   `.loradb` path under `database_dir`, or the current directory when no
   *   directory is provided.
   */
  constructor(databaseName?: string | null | undefined, databaseDir?: string | null | undefined, syncMode?: "groupSync" | null | undefined, groupSyncIntervalMs?: number | null | undefined, walDir?: string | null | undefined, snapshotDir?: string | null | undefined, snapshotEveryCommits?: number | null | undefined, snapshotKeepOld?: number | null | undefined, snapshotOptions?: Record<string, any> | null | undefined)
  /**
   * Execute a Lora query on the libuv threadpool.
   *
   * The returned JS Promise resolves with `{ columns, rows }`. Values
   * follow the shared `LoraValue` TypeScript union: primitives pass
   * through, nodes / relationships / paths carry a `kind` discriminator,
   * and temporal / spatial values are tagged objects.
   *
   * Errors surface as `LoraError` in the TS wrapper with a narrowed
   * `code` from the `LoraErrorCode` union (e.g. `LORA_PARSE`,
   * `LORA_INVALID_PARAMS`, `LORA_INTERNAL`).
   * Execute a Lora query and return the encoded result buffer.
   *
   * The TS wrapper decodes the buffer into the canonical
   * `{ columns, rows }` shape. Encoding the result on the libuv
   * worker and transferring it to JS as a single Buffer avoids the
   * per-cell napi syscalls that otherwise dominate wall-clock cost
   * on bulk reads. See `crates/bindings/lora-node/src/encode.rs`
   * for the wire format.
   */
  execute(query: string, params?: Record<string, any> | null | undefined): Promise<Buffer>
  /**
   * Compile a query and return its execution plan without running it.
   *
   * Unlike [`Self::execute`], this never invokes the executor — even
   * for mutating queries (`CREATE`, `MERGE`, `SET`, `DELETE`,
   * `REMOVE`) `explain()` produces no side effects. The returned
   * object describes the operator tree the executor *would* run.
   */
  explain(query: string, params?: Record<string, any> | null | undefined): Promise<LoraQueryPlan>
  /**
   * Execute a query and return runtime metrics alongside the plan.
   *
   * **`profile()` runs the query for real.** Mutating queries
   * produce the same side effects as `execute()`. Use `explain()`
   * to inspect a mutating plan without running it.
   */
  profile(query: string, params?: Record<string, any> | null | undefined): Promise<LoraQueryProfile>
  /**
   * Open a true native row stream.
   *
   * The returned handle owns the Rust `QueryStream`, so rows are pulled
   * from the executor one `next()` call at a time instead of materializing
   * the whole result up front.
   */
  openStream(query: string, params?: Record<string, any> | null | undefined): number
  streamColumns(streamId: number): string[]
  streamNext(streamId: number): Record<string, any> | null
  streamClose(streamId: number): void
  /**
   * Execute multiple statements inside one core transaction.
   *
   * `statements` is an array of `{ query, params? }` objects. Results are
   * returned in statement order. If any statement fails, the transaction is
   * rolled back by dropping the native transaction before commit.
   */
  transaction(statements: Array<{ query: string; params?: Record<string, any> | null }>, mode?: "read_write" | "read_only" | "readwrite" | "readonly" | null | undefined): Promise<Buffer[]>
  /** Force pending WAL bytes and the portable archive mirror to disk. */
  sync(): Promise<void>
  /**
   * Drop every node and relationship, returning the database to an empty
   * state.
   */
  clear(): Promise<void>
  /** Number of nodes in the graph. Synchronous. */
  nodeCount(): number
  /** Number of relationships in the graph. Synchronous. */
  relationshipCount(): number
  /**
   * Release the native database handle. Idempotent.
   *
   * Any query already dispatched to the libuv threadpool keeps its cloned
   * handle until it finishes; new operations fail with `database is closed`.
   */
  dispose(): void
  /**
   * Save the graph to a snapshot file. Atomic: the target is only
   * replaced once the whole payload has been written + fsync'd.
   * Synchronous — snapshots are usually infrequent and running on the
   * event loop dodges the cost of a thread hop for small graphs.
   */
  saveSnapshot(path: string, options?: Record<string, any> | null | undefined): { formatVersion: number; nodeCount: number; relationshipCount: number; walLsn: number | null }
  /** Serialize the current graph into snapshot bytes. */
  saveSnapshotBuffer(options?: Record<string, any> | null | undefined): Buffer
  /** Replace the current graph state with a snapshot loaded from disk. */
  loadSnapshot(path: string, options?: Record<string, any> | null | undefined): { formatVersion: number; nodeCount: number; relationshipCount: number; walLsn: number | null }
  /** Replace the current graph state with a snapshot loaded from bytes. */
  loadSnapshotBuffer(bytes: Uint8Array | Buffer, options?: Record<string, any> | null | undefined): { formatVersion: number; nodeCount: number; relationshipCount: number; walLsn: number | null }
}
