/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Lora graph database handle exposed to Node.
 *
 * Wraps an `Arc<Database<InMemoryGraph>>`; the same handle is cloned
 * onto the libuv threadpool for each `execute()` call. Multiple
 * concurrent queries against the same `Database` can share read-only
 * work; writes serialize on the inner store's write lock without
 * blocking the JS event loop.
 *
 * With no constructor arg the database is purely in-memory. Passing a
 * database name plus `database_dir` enables archive-backed persistence: the
 * binding opens or creates the serialized `.loradb` path under
 * `database_dir`, replays committed writes on boot, and then serves queries
 * against the recovered graph.
 */
export declare class Database {
  /**
   * Construct a database.
   *
   * - no args => fresh in-memory graph.
   * - `database_name` without `database_dir` => fresh named in-memory graph
   *   (the name is validated, but no `.loradb` file is opened).
   * - `database_name` with `database_dir` => archive-backed graph rooted at
   *   the serialized `.loradb` path under `database_dir`.
   */
  constructor(databaseName?: string | null | undefined, databaseDir?: string | null | undefined)
  /**
   * Execute a Lora query on the libuv threadpool.
   *
   * The returned JS Promise resolves with `{ columns, rows }`. Values
   * follow the shared `LoraValue` TypeScript union: primitives pass
   * through, nodes / relationships / paths carry a `kind` discriminator,
   * and temporal / spatial values are tagged objects.
   *
   * Errors surface as `LoraError` in the TS wrapper with a narrowed
   * `code` (`LORA_ERROR`, `INVALID_PARAMS`).
   */
  execute(query: string, params?: Record<string, any> | null | undefined): Promise<{ columns: string[]; rows: Array<Record<string, any>> }>
  /**
   * Open a true native row stream.
   *
   * The returned handle owns the Rust `QueryStream`, so rows are pulled
   * from the executor one `next()` call at a time instead of materializing
   * the whole result up front.
   */
  openStream(query: string, params?: Record<string, any> | null | undefined): number
  streamColumns(streamId: number): string[]
  streamNext(streamId: number): Record<string, any> | null
  streamClose(streamId: number): void
  /**
   * Execute multiple statements inside one core transaction.
   *
   * `statements` is an array of `{ query, params? }` objects. Results are
   * returned in statement order. If any statement fails, the transaction is
   * rolled back by dropping the native transaction before commit.
   */
  transaction(statements: Array<{ query: string; params?: Record<string, any> | null }>, mode?: "read_write" | "read_only" | "readwrite" | "readonly" | null | undefined): Promise<Array<{ columns: string[]; rows: Array<Record<string, any>> }>>
  /**
   * Drop every node and relationship, returning the database to an empty
   * state. Useful for test isolation. Synchronous — constant-time.
   */
  clear(): void
  /** Number of nodes in the graph. Synchronous. */
  nodeCount(): number
  /** Number of relationships in the graph. Synchronous. */
  relationshipCount(): number
  /**
   * Release the native database handle. Idempotent.
   *
   * Any query already dispatched to the libuv threadpool keeps its cloned
   * handle until it finishes; new operations fail with `database is closed`.
   */
  dispose(): void
  /**
   * Save the graph to a snapshot file. Atomic: the target is only
   * replaced once the whole payload has been written + fsync'd.
   * Synchronous — snapshots are usually infrequent and running on the
   * event loop dodges the cost of a thread hop for small graphs.
   */
  saveSnapshot(path: string): { formatVersion: number; nodeCount: number; relationshipCount: number; walLsn: number | null }
  /** Serialize the current graph into snapshot bytes. */
  saveSnapshotToBytes(): Buffer
  /** Replace the current graph state with a snapshot loaded from disk. */
  loadSnapshot(path: string): { formatVersion: number; nodeCount: number; relationshipCount: number; walLsn: number | null }
  /** Replace the current graph state with a snapshot loaded from bytes. */
  loadSnapshotFromBytes(bytes: Uint8Array | Buffer): { formatVersion: number; nodeCount: number; relationshipCount: number; walLsn: number | null }
}
