/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * In-memory Lora graph database handle exposed to Node.
 *
 * Holds an `Arc<Mutex<InMemoryGraph>>`; the inner store is moved onto the
 * libuv threadpool for each `execute()` call. Multiple concurrent queries
 * against the same `Database` serialise on the mutex but do not block the
 * JS event loop.
 */
export declare class Database {
  /** Construct an empty in-memory database. */
  constructor()
  /**
   * Execute a Lora query on the libuv threadpool.
   *
   * The returned JS Promise resolves with `{ columns, rows }`. Values
   * follow the shared `LoraValue` TypeScript union: primitives pass
   * through, nodes / relationships / paths carry a `kind` discriminator,
   * and temporal / spatial values are tagged objects.
   *
   * Errors surface as `LoraError` in the TS wrapper with a narrowed
   * `code` (`LORA_ERROR`, `INVALID_PARAMS`).
   */
  execute(query: string, params?: Record<string, any> | null | undefined): Promise<{ columns: string[]; rows: Array<Record<string, any>> }>
  /**
   * Drop every node and relationship, returning the database to an empty
   * state. Useful for test isolation. Synchronous — constant-time.
   */
  clear(): void
  /** Number of nodes in the graph. Synchronous. */
  nodeCount(): number
  /** Number of relationships in the graph. Synchronous. */
  relationshipCount(): number
}
