module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: ['index', 'why'],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/playground',
        'getting-started/installation',
        'getting-started/node',
        'getting-started/python',
        'getting-started/wasm',
        'getting-started/go',
        'getting-started/ruby',
        'getting-started/rust',
        'getting-started/server',
        'getting-started/tutorial',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/graph-model',
        'concepts/nodes',
        'concepts/relationships',
        'concepts/properties',
        'concepts/schema-free',
        'concepts/result-formats',
      ],
    },
    {
      type: 'category',
      label: 'Queries',
      collapsed: false,
      items: [
        'queries/index',
        'queries/match',
        'queries/create',
        'queries/where',
        'queries/indexes',
        'queries/constraints',
        'queries/return-with',
        'queries/set-delete',
        'queries/unwind-merge',
        'queries/aggregation',
        'queries/ordering',
        'queries/paths',
        'queries/parameters',
        'queries/examples',
        'queries/cheat-sheet',
      ],
    },
    {
      type: 'category',
      label: 'Functions',
      collapsed: false,
      items: [
        'functions/overview',
        'functions/aggregation',
        'functions/string',
        'functions/math',
        'functions/number',
        'functions/list',
        'functions/map',
        'functions/temporal',
        'functions/spatial',
        'functions/vectors',
        'functions/utility',
      ],
    },
    {
      type: 'category',
      label: 'Data Types',
      collapsed: false,
      items: [
        'data-types/overview',
        'data-types/scalars',
        'data-types/lists-and-maps',
        'data-types/temporal',
        'data-types/spatial',
        'data-types/vectors',
      ],
    },
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      items: [
        'api/http',
        // The GraphQL layer has its own navbar tab and sidebar (below);
        // this link keeps it reachable from the main docs tree.
        { type: 'link', label: 'GraphQL', href: '/docs/graphql' },
      ],
    },
    {
      type: 'category',
      label: 'Guides & Reference',
      collapsed: false,
      items: ['cookbook', 'snapshot', 'wal', 'performance', 'errors', 'limitations', 'troubleshooting'],
    },
    {
      type: 'category',
      label: 'Developer',
      collapsed: true,
      items: ['developer/functions'],
    },
  ],
  // Rendered under the "GraphQL" navbar tab. Pages stay at
  // /docs/graphql/*, so existing links keep working.
  graphql: [
    {
      type: 'category',
      label: 'Start',
      collapsed: false,
      items: ['graphql/index', 'graphql/tutorial', 'graphql/serving'],
    },
    {
      type: 'category',
      label: 'Model',
      collapsed: false,
      items: [
        'graphql/directives',
        'graphql/relationships',
        'graphql/many-to-many',
        'graphql/cypher-fields',
      ],
    },
    {
      type: 'category',
      label: 'The API',
      collapsed: false,
      items: ['graphql/generated-api', 'graphql/examples'],
    },
    {
      type: 'category',
      label: 'Access control',
      collapsed: false,
      items: [
        'graphql/authentication',
        'graphql/authorization',
        'graphql/authorization-recipes',
      ],
    },
    {
      type: 'category',
      label: 'Operate',
      collapsed: false,
      items: [
        'graphql/smart-layer',
        'graphql/observability',
        'graphql/testing',
        'graphql/cli',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'graphql/api-reference',
        'graphql/errors',
        'graphql/translation-rules',
        'graphql/limitations',
        'graphql/migrating-from-neo4j',
      ],
    },
  ],
};
