module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: ['index', 'why'],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/node',
        'getting-started/python',
        'getting-started/wasm',
        'getting-started/go',
        'getting-started/ruby',
        'getting-started/tutorial',
        {
          type: 'category',
          label: 'Other runtimes',
          collapsed: true,
          items: [
            'getting-started/rust',
            'getting-started/server',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/graph-model',
        'concepts/nodes',
        'concepts/relationships',
        'concepts/properties',
        'concepts/schema-free',
        'concepts/result-formats',
      ],
    },
    {
      type: 'category',
      label: 'Queries',
      collapsed: false,
      items: [
        'queries/index',
        'queries/match',
        'queries/create',
        'queries/where',
        'queries/return-with',
        'queries/set-delete',
        'queries/unwind-merge',
        'queries/aggregation',
        'queries/ordering',
        'queries/paths',
        'queries/parameters',
        'queries/examples',
        'queries/cheat-sheet',
      ],
    },
    {
      type: 'category',
      label: 'Functions',
      collapsed: false,
      items: [
        'functions/overview',
        'functions/aggregation',
        'functions/string',
        'functions/math',
        'functions/list',
        'functions/temporal',
        'functions/spatial',
        'functions/vectors',
      ],
    },
    {
      type: 'category',
      label: 'Data Types',
      collapsed: false,
      items: [
        'data-types/overview',
        'data-types/scalars',
        'data-types/lists-and-maps',
        'data-types/temporal',
        'data-types/spatial',
        'data-types/vectors',
      ],
    },
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      items: ['api/http'],
    },
    {
      type: 'category',
      label: 'Guides & Reference',
      collapsed: false,
      items: ['cookbook', 'limitations', 'troubleshooting'],
    },
  ],
};
